#!/bin/bash

#install and set up simc
git clone https://github.com/simulationcraft/simc.git
cd simc/engine
make -j4 OPENSSL=1 optimized
ln -s simc ~/.local/
echo "p3ch4uzw7rnj5c93dbe7b9r6q5fg2v5f" > ${HOME}/.simc_apikey

#set up jupyter widgets
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust index.ipynb
